version: 2

sources:
  - name: bronze
    # Deixamos o schema vazio ou removemos para o dbt não tentar prefixar nada
    tables:
      - name: stock_prices
        # O segredo: Não use aspas simples por fora, use apenas as crases do Spark
        identifier: delta.`/home/victor_goveia/projects/open_financial_lakehouse/data/bronze/stock_prices`